# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]   # change to 'master' if your default branch is master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If your site is just static files (index.html, app.js, etc.),
      # no build is needed. If you later add a build, do it here and
      # change the 'path' below to your build output directory.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # publish the repository root (contains index.html)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
